### PR TITLE
[S2GRAPH-96]: Remove unmanaged dependencies(asynchbase) and speficy it on build.sbt

### PR DESCRIPTION
**Pull request by SteamShon**
+ remove unmanaged dependency(asynchbase) from project folder.
+ instead add it on build.sbt.

### CODE REVIEW

**Comment by daewon** [comment]
+1

**Comment by SteamShon** [comment]
after merge #68 PR, I can successfully finish test cases by issuing `sbt test` multiple times.

**Comment by daewon** [comment]
Error occurred on test.

```bash
sbt clean test
```

```
[info] Exception encountered when attempting to run a suite with class name: org.apache.s2graph.core.Integrate.CrudTest *** ABORTED *** (131 milliseconds)
[info]   java.lang.NoSuchMethodError: org.jboss.netty.util.HashedWheelTimer.<init>(Ljava/util/concurrent/ThreadFactory;Lorg/jboss/netty/util/ThreadNameDeterminer;JLjava/util/concurrent/TimeUnit;I)V
[info]   at org.hbase.async.HBaseClient.newTimer(HBaseClient.java:629)
[info]   at org.hbase.async.HBaseClient.defaultChannelFactory(HBaseClient.java:657)
[info]   at org.hbase.async.HBaseClient.<init>(HBaseClient.java:557)
[info]   at org.apache.s2graph.core.storage.hbase.AsynchbaseStorage$.makeClient(AsynchbaseStorage.scala:76)
[info]   at org.apache.s2graph.core.storage.hbase.AsynchbaseStorage.<init>(AsynchbaseStorage.scala:93)
[info]   at org.apache.s2graph.core.Graph$.initStorage(Graph.scala:355)
[info]   at org.apache.s2graph.core.Graph.<init>(Graph.scala:368)
[info]   at org.apache.s2graph.core.Integrate.IntegrateCommon$class.beforeAll(IntegrateCommon.scala:44)
[info]   at org.apache.s2graph.core.Integrate.CrudTest.beforeAll(CrudTest.scala:25)
[info]   at org.scalatest.BeforeAndAfterAll$class.beforeAll(BeforeAndAfterAll.scala:187)
[info]   at org.apache.s2graph.core.Integrate.CrudTest.beforeAll(CrudTest.scala:25)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:253)
[info]   at org.apache.s2graph.core.Integrate.CrudTest.run(CrudTest.scala:25)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:466)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:677)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:235)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:745)

```

**Comment by daewon** [comment]
After library Dependence order change, it works.
- from last to first.

```
libraryDependencies ++= Seq(
  "org.hbase" % "asynchbase" % "1.7.2-S2GRAPH" from "https://github.com/SteamShon/asynchbase/raw/mvn-repo/org/hbase/asynchbase/1.7.2-S2GRAPH/asynchbase-1.7.2-S2GRAPH-jar-with-dependencies.jar",
  "ch.qos.logback" % "logback-classic" % "1.1.2",
  "com.typesafe" % "config" % "1.2.1",
  "com.typesafe.play" %% "play-json" % Common.playVersion,
  "com.typesafe.akka" %% "akka-actor" % "2.3.4",
  "com.google.guava" % "guava" % "12.0.1" force(), // use this old version of guava to avoid incompatibility
  "org.apache.hbase" % "hbase-client" % Common.hbaseVersion exclude("org.slf4j", "*"),
  "org.apache.hbase" % "hbase-common" % Common.hbaseVersion exclude("org.slf4j", "*"),
  "org.apache.hbase" % "hbase-server" % Common.hbaseVersion exclude("org.slf4j", "*") exclude("com.google.protobuf", "*"),
  "org.apache.hbase" % "hbase-hadoop-compat" % Common.hbaseVersion exclude("org.slf4j", "*"),
  "org.apache.hbase" % "hbase-hadoop2-compat" % Common.hbaseVersion exclude("org.slf4j", "*"),
  "org.apache.kafka" % "kafka-clients" % "0.8.2.0" exclude("org.slf4j", "*") exclude("com.sun.jdmk", "*") exclude("com.sun.jmx", "*") exclude("javax.jms", "*"),
  "commons-pool" % "commons-pool" % "1.6",
  "org.scalatest" %% "scalatest" % "2.2.4" % "test",
  "org.scalikejdbc" %% "scalikejdbc" % "2.1.+",
  "com.h2database" % "h2" % "1.4.192",
  "com.github.danielwegener" % "logback-kafka-appender" % "0.0.4"
)

```

**Comment by SteamShon** [comment]
@daewon Thanks for the report. It help me to narrow down the cause of this problem.

I think io.netty version is conflicting here since asynchbase require netty version `3.9.4.Final`, and hbase-client + hbase-server are using `4.0.23.Final`. 

I added below line to make sure asynchbase to use right version.

```
"io.netty" % "netty" % "3.9.4.Final" force()
```

After this is prepend in-front of asynchbase, I can finally get all success on every test cases.

Please git pull this and tell me what you think!

**Comment by daewon** [comment]
@SteamShon It works!
+1

This commit contains `s2core/lib` it should be removed.

**Comment by SteamShon** [comment]
@daewon I just did `git rm -rf s2core/lib`. Thanks for the pointing out.

**Pull request closed without merging**
