### PR TITLE
[S2GRAPH-136]: Validate TinkerPop3 interface with gremlin-test suite.

### PR DESCRIPTION
**Pull request by SteamShon**
- define initial version of features.
- setup gremlin-test environment.

### CODE REVIEW

**Comment by echarles** [comment]
A few feedbacks after testing this branch:

- The tinkerpop integration tests are configured with mysql (changed it to h2) and an external hbase cluster: is this what we want

- S2GraphStructureIntegrateTest returns `he StructureIntegrateSuite will not run for this Graph until it is publicly acknowledged with the @OptIn annotation on the Graph instance itself`

- S2GraphStructureStandardTest has many methods: most of them are ignored with "org.junit.AssumptionViolatedException: S2Graph does not support all of the features required by this test so it will be ignored:" - Some are green : Great1 - others are red (eg: shouldRemoveEdges with java.lang.IllegalArgumentException at org.apache.s2graph.core.S2Vertex.addEdge(S2Vertex.scala:198))

Happy to further work here to get more green methods - Where to start?

**Comment by SteamShon** [comment]
@echarles 

Thanks for feedbacks

- The tinkerpop integration tests are configured with mysql (changed it to h2) and an external hbase cluster: is this what we want?

good point. I think it would be better for us to configure our tests can be run without any setup(like external hbase cluster). I suggest to change this to use h2 + embedded standalone hmaster as default for test to easy testing environment setup. I have naive version for this change, and I will push this commit under this PR. 

- S2GraphStructureIntegrateTest returns he StructureIntegrateSuite will not run for this Graph until it is publicly acknowledged with the @OptIn annotation on the Graph instance itself

I think IntegrateTest is optional(based on [here](http://tinkerpop.apache.org/docs/current/dev/provider/#validating-with-gremlin-test)). I am still struggling to pass `StructureStandardSuite`(not many green yet) and I think once I am done with`StructureStandardSuite` then start dig it. 

I think best way to get started is running `StructureStandardSuite` and find out failed cases and debug them and you can start work by comment out @Graph.OptOuts(S2Graph.scala:532). 

Many test cases in `StructureStandardSuite`  expect their own Edge/Vertex/Property schema with specific data, so figuring out schema then place them under `S2GraphProvider.loadGraphData`, then comment out that OptOut, then debug it...It may not right way, but since I have very limited knowledge on gremlin-test, I was learning in this hard way. happy to learn better way.

**Comment by spmallette** [comment]
Just a quick note to mention that as of TinkerPop 3.2.4 all the groovy related test suites are now deprecated:

http://tinkerpop.apache.org/docs/3.2.4/upgrade/#_deprecated_optin

That should save you a few tests to worry about implementing. I guess we missed removing all references to those from the provider docs.

**Comment by daewon** [comment]
@SteamShon I've read the whole code.

I do not have a lot of knowledge about tinkerpop, so it's difficult to get accurate reviews, but there are no code errors.

The problem is I do not know how to run this test.

I checked out the code from #112 () in steamshon's github repo, and I ran `S2GraphProcessStandardTest` in IntelliJ, but the test does not work.

What should I do?

**Comment by daewon** [comment]
@SteamShon 
Sorry. There was a problem with my Docker on my system.

It has been fixed now and I have checked that it passes the `StructureStandardTest` and` ProcessStandardTest` tests.

**Comment by spmallette** [comment]
I see this is merged to master - does this mean that s2graph is TinkerPop compliant now? If so, any ideas on when there will be a release of s2graph with TinkerPop support?

**Comment by SteamShon** [comment]
Hi @spmallette 

I think merging this issue means that s2graph is TinkerPop compliant basically.(only OLTP so far).
Even though Gremlin-Core is tested, I think s2graph community still need to work on following.

1. provide provider optimization, we have none currently. 
2. full text search predicate is not currently supported(as @echarles pointed out)
3. provide gremlin plugin 
4. make sure tinkerpop stack works correctly.

I closed https://issues.apache.org/jira/browse/S2GRAPH-136 since set up above as separate tasks for more helps from community.

we can decide whether we release the alpha version without any provider optimization, then improve above issues on next next release(0.3.0-incubating?), or wait next release until all of above issues addressed.

I was about to open up discussion on the next release schedule and what's will be included, so let me 
open up discussion and see when the next release could be.

Personally, I am +1 on release early alpha version then improve them, but it depends on what other folks think. if we choose to release early alpha version then improve it, then I guess we can release on late this month.

**Comment by spmallette** [comment]
Having the basic tests working is a good first step - it's nice to see that you have gotten that far. I think that the TinkerPop community would really like to see S2Graph listed as a TinkerPop provider. I would say that you are pretty close to meeting our policies for listing:

http://tinkerpop.apache.org/policy.html

**Pull request closed without merging**
