### PR TITLE
[S2GRAPH-14] Abstract HBase specific methods in Management and Label.

### PR DESCRIPTION
**Pull request by SteamShon**
* Remove Management.createService from Label/Service.
* Add Management class and move createService/createLabel/createTable from Management object into Management class.
* Refactor caller of above methods according to changes.

### CODE REVIEW

**Comment by daewon** [comment]
:+1:

**Comment by hsleep** [comment]
@SteamShon 
Please resolve conflicts.

**Comment by SteamShon** [comment]
@hsleep merged changed master into this PR. please review this again.

**Comment by emeth-kim** [comment]
+1 

This pr gives us a chance to add various backend storages along with the storage abstraction.

**Comment by hsleep** [comment]
:+1:

**Comment by daewon** [comment]
+1 
:+1:

**Pull request closed without merging**
