### PR TITLE
[S2GRAPH-16] Performance tunning on where parser

### PR DESCRIPTION
**Pull request by SteamShon**
Add InWithoutParent on Where parser for performance tunning.

### CODE REVIEW

**Comment by daewon** [comment]
Good point.
+1

**Comment by emeth-kim** [comment]
This code works fine and improves query performance in the Inhouse environment.

+1

**Comment by hsleep** [comment]
I have tested this PR using below command.
```
sbt test
```

But following errors are occurred at the compile time.
```
...
[error] /Users/hsleep/git/incubator-s2graph/s2core/src/test/scala/com/kakao/s2graph/core/parsers/WhereParserTest.scala:34: type mismatch;
[error]  found   : Map[String,com.kakao.s2graph.core.mysqls.Label]
[error]  required: com.kakao.s2graph.core.mysqls.Label
[error]     val whereOpt = WhereParser(labelMap).parse(sql)
[error]                                ^
[error] one error found
...
```

**Comment by SteamShon** [comment]
@hsleep I fixed above error on test cases. 
@daewon , @emeth-kim please review this again

**Comment by hsleep** [comment]
:+1: Looks good to me.

**Comment by emeth-kim** [comment]
LGTM +1

**Comment by daewon** [comment]
[info] 3 examples, 0 failure, 0 error
[info] Passed: Total 11, Failed 0, Errors 0, Passed 11
[success] Total time: 220 s, completed 2016. 1. 15 오후 2:56:46

+1

**Pull request closed without merging**
