### PR TITLE
[S2GRAPH-21] Change PostProcessBenchmarkSpec not to store and fetch test data from storage

### PR DESCRIPTION
**Pull request by SteamShon**
decoupled creating service/label from benchmark test cases.

### CODE REVIEW

**Comment by daewon** [comment]
I agree to  remove `play framework` dependency
+1

**Comment by SteamShon** [comment]
@daewon, @hsleep , @emeth-kim, since some PR has been merged into master after opening this PR, I merged master into this PR so we can just merge them after review. Please review and give feedbacks.

**Comment by emeth-kim** [comment]
+1

**Comment by hsleep** [comment]
+1

**Pull request closed without merging**
