### PR TITLE
[S2GRAPH-131]:  Add actual implementation on interfaces from TinkerPop3 structure package.

### PR DESCRIPTION
**Pull request by SteamShon**
- Change core.Edge/Vertex/Graph to core.S2Edge/S2Vertex/S2Graph.
- Implement base interfaces for tinkerpop3 structure package.

### CODE REVIEW

**Comment by daewon** [comment]
I have verified that the existing test cases work well, and the code seems to be fine.

It seems to be able to make the part that returns `util.Iterator` somewhat efficient, and this part will be created as a separate issue.

P.s: 'thinkerpop' looks like a very interesting project. But I still do not have enough knowledge of 'tinkerpop' to review the code.

+1

**Comment by HyunsungJo** [comment]
* With HBase + MySQL on local Mac all the tests look good.
* Is there any way that we can test TinkerPop functionality with this PR?

**Comment by daewon** [comment]
@HyunsungJo You can see Tinkerpop related queries from the link below. 

https://github.com/apache/incubator-s2graph/blob/42e4fa1311a9bf883919a0f96d97e81bccb5cd3b/s2core/src/test/scala/org/apache/s2graph/core/Integrate/tinkerpop/S2GraphTest.scala

**Comment by SteamShon** [comment]
@HyunsungJo there is actually no test cases for tinkerpop parts. I only added the very basic. I think the right way to test if we are implementing tp3 correctly running gremlin test suite. To run gremlin test suite, I guess we need to decide which features we are going to provide(I briefly mentioned on https://lists.apache.org/thread.html/da3434f2338f8605909c40758c2c4ef35c1a0bee27eba6951316a3fb@%3Cdev.s2graph.apache.org%3E) since test suite decide which test to run based on this feature on Graph class(Correct me if I am wrong). So in this pr, I more focused on providing naive implementation and make sure our existing code does not break. I suggest to separate validation on tinkerpop interface through gremlin test suite to other issue.

**Comment by SteamShon** [comment]
@daewon 

```It seems to be able to make the part that returns util.Iterator somewhat efficient, and this part will be created as a separate issue.``` 

Correct me if I am wrong, but I think you are suggesting providing iterator `util.Iterator[Edge]` on `StepResult`. 

Since there is only one way to iterate edges by iterate through `Seq[EdgeWithScore]`, we had to run map on this sequence of `EdgeWithScore` to get util.Iterator[Edge], which tinkerpop interface expect. 

I think it is very good idea to provide iterator `util.Iterator[Edge]` in `StepResult` so we can just simply return it when it is necessary rather than create new sequence of Edge. Can you please create a separate Jira issue for this?

**Comment by daewon** [comment]
I think it is better to treat the optimize for this part that returns `util.iterator[Edge]` as a separated issue from this.

After S2GRAPH-131 issue is resolved, i will separate it into new issue.

**Comment by SteamShon** [comment]
@HyunsungJo at #100 you asked why `IndexEdgeTest` and `EdgeTest` are commented out. 

1. S2EdgeTest
I think testing `toString` does not make much sense and I think we should delete `test("toLogString")`  since I don't think it is testing any thing actually.

2. IndexEdgeTest
It is important test cases since it make sure that serialize/deserialize work correctly. I just fixed it and pushed changes here rather than #100 PR. 

Sorry again to make confusing. Unless objection, I am going to merge this.

@daewon , @HyunsungJo Thanks for your reviews~!

**Pull request merged**
