### PR TITLE
[S2GRAPH-129]: Restrict direct access on Edge's properties from other classes.

### PR DESCRIPTION
**Pull request by SteamShon**
- add tp3 as dependencies.
- make propsWithTs as private.

Note that interface is not implemented on this PR. Few separate issues will be followed up base on this PR.

### CODE REVIEW

**Comment by daewon** [comment]
Functions that deal with class internal variables are considered to be inside classes

+1

**Comment by HyunsungJo** [comment]
* All tests pass in my local environment.
* `CanInnerValLike` is this the best naming of this object? If so, LGTM.

**Comment by daewon** [comment]
@HyunsungJo The name 'CanInnerValLike[A]' is a name that means type A can be treated as type 'innerValLike'.

Now I think it does not seem appropriate. I would like another opinion.

**Comment by SteamShon** [comment]
@HyunsungJo do you have any suggestion?

**Comment by SteamShon** [comment]
@HyunsungJo I was waiting more `proper` name, but I think we can refactor the name `CanInnerValLike[A]` when we come up with better name. I am going to merge this if there is no objection.

**Pull request merged**
