### PR TITLE
[S2GRAPH-93]: Remove MySQL JDBC driver.

### PR DESCRIPTION
**Pull request by SteamShon**
- remove mysql-connector-java from dependencies.
- change default metastore to use H2 instead of mysql.
- fix test cases to adopt H2 as default metastore.

### CODE REVIEW

**Comment by daewon** [comment]
i met two error on running test with cmd 'sbt 'project s2core' test'

1. WeakLabelDeleteTest is fail.
```
[info] WeakLabelDeleteTest:
[info] - test weak consistency select (74 milliseconds)
[info] - test weak consistency delete *** FAILED *** (17 milliseconds)
[info]   0 was not equal to 4 (WeakLabelDeleteTest.scala:49)
```

2. test hang on QueryTest

**Comment by SteamShon** [comment]
@daewon Thanks for the feedback.

I just run same command `sbt "project s2core" test` and there is no failed TC. 
I am wondering if there was any Error or Exception during test causing test failure.

**Comment by SteamShon** [comment]
@daewon 

since limit -1 fetch Int.MaxValue size of edges, it reserver lots of memory on HBaseClient. 
I think memory on HBase cause the TC failed. I removed problematic limit parameter on `QueryTest` to reduce memory usage on test.

now `sbt "project s2core" test` gives me success. can you please re-test this?

**Comment by hsleep** [comment]
@SteamShon 
I've succesfully tested this PR.

**Comment by daewon** [comment]
+1 
After commit(fcd9fb9) It works!

**Pull request closed without merging**
