### PR TITLE
[S2GRAPH-148]: Provide Gremlin Plugin

### PR DESCRIPTION
**Pull request by SteamShon**
- add README.md.
- add examples on s2graph_gremlin.
- add java interface for build global index.
- add helper on Management.
- add S2GraphFactory.
- update build.sbt
- add s2graph_gremlin as subproject for gremlin plugin.
- upgrate sbt-assembly.

### CODE REVIEW

**Comment by daewon** [comment]
+1 
It works well

**Comment by daewon** [comment]
@SteamShon I found an error situation during my retest with my colleague.
`rm -rf var storage ; sbt 'project s2core' 'test-only *GlobalIndexTest*'`

In a clean environment, if the test fails with the above command, the first execution fails and the next execution succeeds.

```scala
  def findAll(elementType: String, useCache: Boolean = true)(implicit session: DBSession = AutoSession): Seq[GlobalIndex] = {
    lazy val ls = sql"""select * from global_indices where element_type = $elementType""".map { rs => GlobalIndex(rs) }.list.apply
    if (useCache) {
      listCache.withCache(s"findAll:elementType=$elementType") {
        putsToCache(ls.map { globalIndex =>
          val cacheKey = s"elementType=${globalIndex.elementType}:indexName=${globalIndex.indexName}"
          cacheKey -> globalIndex
        })
        ls
      }
    } else {
      ls
    }
  }
```

The above method does not return `ls` in the `useCache` situation (`ls` is updated in the background thread)

```scala
`rm -rf var storage ; sbt 'project s2core' 'test-only *GlobalIndexTest*'`

클린한 환경에서 위 명령어로 테스트를 실패시 첫 실행은 실패하고 그 다음 실행은 성공을 한다.

```
  def findAll(elementType: String, useCache: Boolean = true)(implicit session: DBSession = AutoSession): Seq[GlobalIndex] = {
    lazy val ls = sql"""select * from global_indices where element_type = $elementType""".map { rs => GlobalIndex(rs) }.list.apply
    if (useCache) {
      listCache.withCache(s"findAll:elementType=$elementType") {
        putsToCache(ls.map { globalIndex =>
          val cacheKey = s"elementType=${globalIndex.elementType}:indexName=${globalIndex.indexName}"
          cacheKey -> globalIndex
        })
        ls
      }
    } else {
      ls
    }
  }
```

위 메서드에서 보면 `useCache`인 상황에서 ls를 반환하지 않고 있다(ls는 백그라운드에서 업데이트 된다) 이 때문에 위 코드를 아래처럼 수정하면 에러가 발생하지 않는다.

```
  def findAll(elementType: String, useCache: Boolean = true)(implicit session: DBSession = AutoSession): Seq[GlobalIndex] = {
    lazy val ls = sql"""select * from global_indices where element_type = $elementType""".map { rs => GlobalIndex(rs) }.list.apply
    if (useCache) {
      listCache.withCache(s"findAll:elementType=$elementType") {
        putsToCache(ls.map { globalIndex =>
          val cacheKey = s"elementType=${globalIndex.elementType}:indexName=${globalIndex.indexName}"
          cacheKey -> globalIndex
        })
        ls
      }

      ls
    } else {
      ls
    }
  }
```

I changed the code to return `ls` as shown below and confirmed that it works without problems.
Please review the fixed code.

**Comment by daewon** [comment]
The test seems to be failing because it is affected by other tests in parallel.

In this case, it would be correct to modify the TC because the schema is changing at the same time.

There are three ways to fix this problem:

1. Initializing the cache before the test runs does not fail.

`` `Scala
  Test ("findGlobalIndex.") {
    // (weight: 34) AND (weight: [1 TO 100])
    GlobalIndex.listCache.invalidateAll ()
    GlobalIndex.optionCache.invalidateAll ()
`` `

2. Delete the conflict test `S2GraphTest`. (This test does not perform the actual TC)

`` `Scala
Class S2GraphTest extends FunSuite with Matchers with TestCommonWithModels {
`` `

3. Prevent TC in s2core / build.sbt from running in parallel.
`` `
ParallelExecution in Test: = false
`` `

We will fix it in the second method.

**Comment by SteamShon** [comment]
@daewon Thanks for the review and I commented out unnecessary global index on `S2GraphTest` as you suggest.

**Pull request merged**
